# Generated by Django 5.2.7 on 2025-10-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='academic_streams',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='courses.academicstream'),
        ),
    ]
