# Generated by Django 5.2.7 on 2025-10-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chapter_academic_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_chapters', to='courses.chapter'),
        ),
    ]
