# Generated by Django 5.2.7 on 2025-10-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_chapter_dependencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='dependencies',
        ),
    ]
