# Generated by Django 5.2.7 on 2025-10-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_chapter_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='academic_streams',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='courses.academicstream'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='exercise_total_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='exercise_total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
