# Generated by Django 5.2.7 on 2025-10-26 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_moduleenrollment'),
        ('files', '0002_alter_fileuploadsession_upload_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_lessons', to='files.file'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_lessons', to='files.file'),
        ),
    ]
