# Generated by Django 5.2.7 on 2025-10-20 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('courses', '0005_lesson_academic_streams_lesson_exercise_total_mark_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='time_limit',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='exam',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_unlocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('passed', 'Passed'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('passed', 'Passed'), ('failed', 'Failed')], default='submitted', max_length=20)),
                ('solution_pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('student_notes', models.TextField(blank=True, null=True)),
                ('professor_notes', models.TextField(blank=True, null=True)),
                ('professor_review_pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to='users.student')),
            ],
            options={
                'db_table': 'exam_submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
