# Generated by Django 5.2.7 on 2025-10-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='jitsi_room_name',
            field=models.CharField(blank=True, help_text='Jitsi Meet room name for this live session', max_length=200, null=True),
        ),
    ]
