# Generated by Django 5.2.7 on 2025-10-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cv_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
