# Generated by Django 5.2.7 on 2025-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadsession',
            name='upload_token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
