# Generated by Django 5.2.7 on 2025-10-13 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('purchase_approved', 'Purchase Approved'), ('purchase_rejected', 'Purchase Rejected'), ('professor_approved', 'Professor Approved'), ('professor_rejected', 'Professor Rejected'), ('lesson_available', 'Lesson Available'), ('quiz_reminder', 'Quiz Reminder'), ('general', 'General')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
